version: 2.0
jobs:
  build:
    docker:
      - image: hostedgraphite/pythonbuild:hgapp_dep_xenial
    environment:
      CIRCLE_ARTIFACTS: /tmp/artifacts
    steps:
      - checkout
      - run: apt-get update -y
      - run: apt-get install libcurl4-openssl-dev libssl-dev -y
      - run: make install
      - run: make test
      - run: make lint
      - run: cp -r cover $CIRCLE_ARTIFACTS
      - store_artifacts:
          path: /tmp/artifacts
