version: 2.0
jobs:
  build:
    docker:
      - image: hostedgraphite/pythonbuild:hgapp_dep_xenial
    steps:
      - checkout
      - run: apt-get update -y
      - run: apt-get install libcurl4-openssl-dev libssl-dev -y
      - run: make install
      - run: make test
      - run: pip install flake8 coverage httmock mock pyfakefs
      - run: make lint
      - run: make coverage
      - store_artifacts:
          path: htmlcov
